stages:
  - deploy  # Define the stages of the pipeline

deploy:
  stage: deploy  # deploy in EC2 ubuntu
  tags:
    - ticketing  # runner tag to assign runner
  script:
   - apt-get update && apt-get install -y ssh
   - ssh -i ubuntu@15.206.186.138 "sudo -i && cd /var/www/ticketing-backend && git pull origin main && pm2 restart 0"
  only:
    - main  # Only run this job when changes are pushed to the main 
