stages:
  - deploy  # Define the stages of the pipeline

deploy:
  stage: deploy  # deploy in EC2
  tags:
    - ticketing  # runner tag to assign runner
  script:
    # Ensure the .ssh directory exists
    #- mkdir -p ~/.ssh

    # Write the SSH private key (stored in GitLab CI/CD variable) to a file
    #- echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_rsa
    #- chmod 600 ~/.ssh/id_rsa  # Set the correct permissions for the private key

    # Add EC2's IP address to known hosts (alternative to ssh-keyscan)
    - |
      $knownHostsPath = "$HOME/.ssh/authorized_keys"
      $host = "15.206.186.138"
      ssh-keyscan -H $host >> $knownHostsPath

    # Ensure the script stops if any command fails by using $ErrorActionPreference
    - $ErrorActionPreference = "Stop"  # This makes the script stop on errors

    # SSH into EC2 and run commands
    - |
      ssh -o StrictHostKeyChecking=no ubuntu@15.206.186.138 -Command "
        sudo -i;
        cd /var/www/ticketing-backend;
        if ($?) { git pull origin main } else { exit 1 };
        if ($?) { pm2 restart all } else { exit 1 }
      "
  only:
    - main  # Only run this job when changes are pushed to the main branch
